export const designs = [
  {
    id: 1,
    title: "Ansel Collins - Portrait",
    description: "Portrait of the legendary Ansel Collins",
    image: "/assets/designs/AnselCollinsDDExposure.png",
    category: "Branding",
  },
  {
    id: 2,
    title: "Blue Power Showcase",
    description: "A dynamic showcase of blue power and energy",
    image: "/assets/designs/Blue Power Showcase.png",
    category: "Conceptual",
  },
  {
    id: 3,
    title: "Body In",
    description: "Fitness and body positivity concept design",
    image: "/assets/designs/BodyIn.png",
    category: "Logo Design",
  },
  {
    id: 4,
    title: "Chelsea Jo",
    description: "Personal branding design for Chelsea Jo",
    image: "/assets/designs/ChelseaJo.png",
    category: "Personal Branding",
  },
  {
    id: 5,
    title: "Crown of Ester",
    description: "Elegant design featuring a crown motif",
    image: "/assets/designs/CrownOfEster.png",
    category: "Logo Design",
  },
  {
    id: 6,
    title: "D&J Life Coaches",
    description: "Branding for D&J Life Coaching services",
    image: "/assets/designs/D&J-Life-Coaches.png",
    category: "Business",
  },
  {
    id: 7,
    title: "Divine Fitness",
    description: "Logo and branding for Divine Fitness gym",
    image: "/assets/designs/DivineFitness.png",
    category: "Health & Fitness",
  },
  {
    id: 8,
    title: "Fit & Fabulous",
    description: "Inspiring fitness and lifestyle brand design",
    image: "/assets/designs/Fit&Fabulous.png",
    category: "Health & Fitness",
  },
  {
    id: 9,
    title: "Fit and Ageless",
    description: "Branding for age-defying fitness concept",
    image: "/assets/designs/FitAndAgeless.png",
    category: "Health & Fitness",
  },
  {
    id: 10,
    title: "Fllego",
    description: "Modern and minimalist logo design for Fllego",
    image: "/assets/designs/Fllego.jpeg",
    category: "Logo Design",
  },
  {
    id: 11,
    title: "Getting Fit",
    description: "Motivational fitness brand and logo design",
    image: "/assets/designs/GettingFit.png",
    category: "Health & Fitness",
  },
  {
    id: 12,
    title: "Working Towards Hope",
    description: "Inspirational design for personal growth",
    image: "/assets/designs/I Am Working For What I Am Hoping For.png",
    category: "Motivational",
  },
  {
    id: 13,
    title: "Life Relaunch",
    description: "Brand design for personal transformation",
    image: "/assets/designs/I Relaunched My Life.png",
    category: "Personal Development",
  },
  {
    id: 14,
    title: "Living, Not Just Existing",
    description: "Empowering lifestyle brand concept",
    image: "/assets/designs/Im Not Just Existing Im Living.png",
    category: "Lifestyle",
  },
  {
    id: 15,
    title: "Ivy House of Style",
    description: "Elegant branding for Ivy House of Style",
    image: "/assets/designs/IvyHouseOfStyle-Presentation.png",
    category: "Fashion",
  },
  {
    id: 16,
    title: "Lux & Lot",
    description: "Luxury brand design for Lux & Lot",
    image: "/assets/designs/Lux&Lot.JPG",
    category: "Luxury",
  },
  {
    id: 17,
    title: "Momis Homes",
    description: "Warm and inviting design for Momis Homes",
    image: "/assets/designs/MomisHomes.JPG",
    category: "Real Estate",
  },
  {
    id: 18,
    title: "Nella Styles",
    description: "Fashion-forward branding for Nella Styles",
    image: "/assets/designs/NellaStyles.JPG",
    category: "Fashion",
  },
  {
    id: 19,
    title: "Pengin",
    description: "Playful and minimalist penguin-inspired design",
    image: "/assets/designs/Pengin.png",
    category: "Logo Design",
  },
  {
    id: 20,
    title: "Bob Marley - Always Good",
    description: "Tribute design to the legendary Bob Marley",
    image: "/assets/designs/Portrait - Always Good - Bob Marley.png",
    category: "Music",
  },
  {
    id: 21,
    title: "Poshbytoya",
    description: "Sophisticated branding for Poshbytoya",
    image: "/assets/designs/Poshbytoya.png",
    category: "Fashion",
  },
  {
    id: 22,
    title: "Speak Over Yourself",
    description: "Empowering self-affirmation brand concept",
    image: "/assets/designs/Speak Over Yourself.png",
    category: "Motivational",
  },
  {
    id: 23,
    title: "Stronger Than You Think",
    description: "Inspirational fitness and mental strength branding",
    image: "/assets/designs/StrongerThanYouThink copy.png",
    category: "Motivational",
  },
];
