export interface Design {
  id: number;
  title: string;
  description: string;
  image: string;
  category: string;
}

export const designs = [
  {
    id: 1,
    title: "Ansel Collins - Portrait",
    description: "Portrait of the legendary Ansel Collins",
    image: "https://utfs.io/f/ZgFGPQ6nd3OU6P26yQKxE9YgXm7V6CTyfQOkAF0Mei2BLW8G",
    category: "Portrait",
  },
  {
    id: 2,
    title: "Blue Power Showcase",
    description: "A dynamic showcase of blue power and energy",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUF02qlg86aLdAHpe2WwGjXFOk1QgurS7KnU9B",
    category: "Conceptual",
  },
  {
    id: 3,
    title: "Body In",
    description: "Fitness and body positivity concept design",
    image: "https://utfs.io/f/ZgFGPQ6nd3OU9EJLjxLyHTQKCwgec1dzAYtsEJpb978qS6n4",
    category: "Logo",
  },
  {
    id: 4,
    title: "Chelsea Jo",
    description: "Personal branding design for Chelsea Jo",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUUjXj3hmvO12rf3DtwxRyo9GepligmK8IW46n",
    category: "Logo",
  },
  {
    id: 5,
    title: "Crown of Ester",
    description: "Elegant design featuring a crown motif",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUpiUMmRkVYjgcfh3UCHq61rF0ZN5wtW7iybQx",
    category: "Logo",
  },
  {
    id: 6,
    title: "D&J Life Coaches",
    description: "Branding for D&J Life Coaching services",
    image: "https://utfs.io/f/ZgFGPQ6nd3OU45ShqntMQa0FlkPtfTUox5WeJszG29byDXH1",
    category: "Redesign",
  },
  {
    id: 7,
    title: "Divine Fitness",
    description: "Logo and branding for Divine Fitness gym",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUQyoX1RNY7FluNnE48VhzsZodCHeI1O63UGtp",
    category: "Clothing",
  },
  {
    id: 8,
    title: "Fit & Fabulous",
    description: "Inspiring fitness and lifestyle brand design",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUKbESvTdIEOTfulgcUzHk5ASMZxtja4JQrDes",
    category: "Clothing",
  },
  {
    id: 9,
    title: "Fit and Ageless",
    description: "Branding for age-defying fitness concept",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUtdi07VCGxmzL5MPYcNhwOA89vk1K2q3d06to",
    category: "Clothing",
  },
  {
    id: 10,
    title: "Fllego",
    description: "Modern and minimalist logo design for Fllego",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUpnCt6TkVYjgcfh3UCHq61rF0ZN5wtW7iybQx",
    category: "Logo",
  },
  {
    id: 11,
    title: "Getting Fit",
    description: "Motivational fitness brand and logo design",
    image: "https://utfs.io/f/ZgFGPQ6nd3OU85IsZUnXrAGBoWpghOtqS4lCFKvwcsMbjyJd",
    category: "Logo",
  },
  {
    id: 12,
    title: "Working Towards Hope",
    description: "Inspirational design for personal growth",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUzQG0Hmrs94PYEKtD32hjxiqugJelyAZXVnSc",
    category: "Inspirational",
  },
  {
    id: 13,
    title: "Life Relaunch",
    description: "Brand design for personal transformation",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUtxxJXNaCGxmzL5MPYcNhwOA89vk1K2q3d06t",
    category: "Inspirational",
  },
  {
    id: 14,
    title: "Living, Not Just Existing",
    description: "Empowering lifestyle brand concept",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUL8WSipyx7goc5mnqUzB2a3HMkTbYOEPDFerJ",
    category: "Inspirational",
  },
  {
    id: 15,
    title: "Ivy House of Style",
    description: "Elegant branding for Ivy House of Style",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUMSuV9fqYPcX1mQUodizhkS46rqRIlupwV2Zn",
    category: "Logo",
  },
  {
    id: 16,
    title: "Lux & Lot",
    description: "Luxury brand design for Lux & Lot",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUN9aKEDVvWewfTxDtarCnpQ1O5SHicY0LZb9g",
    category: "Logo",
  },
  {
    id: 17,
    title: "Momis Homes",
    description: "Warm and inviting design for Momis Homes",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUEoDM3mUlNorxWUXZ4FsTYa8tfM7Cuhcpk0lV",
    category: "Logo",
  },
  {
    id: 18,
    title: "Nella Styles",
    description: "Fashion-forward branding for Nella Styles",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUEMFGdolNorxWUXZ4FsTYa8tfM7Cuhcpk0lVB",
    category: "Logo",
  },
  {
    id: 19,
    title: "Pengin",
    description: "Playful and minimalist penguin-inspired design",
    image: "https://utfs.io/f/ZgFGPQ6nd3OU7yZVsnzceYxn53J9W7tECpB4RyuwGKfF8HLX",
    category: "Logo",
  },
  {
    id: 20,
    title: "Bob Marley - Always Good",
    description: "Tribute design to the legendary Bob Marley",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUG6L1Zx4hTgCuVMILYbZzBArqdk0ER1aP3lQN",
    category: "Portrait",
  },
  {
    id: 21,
    title: "Poshbytoya",
    description: "Sophisticated branding for Poshbytoya",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUlbWcfNiYokLNVhF9W3S5ZQi4gKb8c2Red6p7",
    category: "Logo",
  },
  {
    id: 22,
    title: "Speak Over Yourself",
    description: "Empowering self-affirmation brand concept",
    image: "https://utfs.io/f/ZgFGPQ6nd3OUFwYlEi86aLdAHpe2WwGjXFOk1QgurS7KnU9B",
    category: "Inspirational",
  },
  {
    id: 23,
    title: "Stronger Than You Think",
    description: "Inspirational fitness and mental strength branding",
    image: "https://utfs.io/f/ZgFGPQ6nd3OURlyQy6jV4jDQ0xSB2kPs5MpnWLNTz7cIhFfu",
    category: "Clothing",
  },
];
